/**
 * InvenSense BMP280 Register Map.
 *
 * THIS SOFTWARE IS PROVIDED BY ATMEL "AS IS" AND ANY EXPRESS OR IMPLIED
 * WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT ARE
 * EXPRESSLY AND SPECIFICALLY DISCLAIMED. IN NO EVENT SHALL ATMEL BE LIABLE FOR
 * ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
 * STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */

#ifndef BMP280_REG_H_INCLUDED
#define BMP280_REG_H_INCLUDED

#define DEVICE_FILE_NAME "bmp280"	// name of the device as it appears in /proc/device
#define DEVICE_NAME "bmp280"
#define MAJOR		232		// major of the device

#define bmp280_suspend	NULL
#define bmp280_resume	NULL

#define BMP280_I2C_CLOCK_SPEED	400000UL // I2C is 400KHz max
#define BMP280_I2C_ADDRESS0x76 // This address is used by BMP280 when ADC0 pin is logic low
#define BMP280_I2C_ADDRESS_ALT	0x77 // This address is used by BMP280 when ADC0 pin is logic high

#define BMP280_REGISTER_DIG_T1		0x88
#define BMP280_REGISTER_DIG_T2		0x8A
#define BMP280_REGISTER_DIG_T3		0x8C

#define BMP280_REGISTER_DIG_P1		0x8E
#define BMP280_REGISTER_DIG_P2		0x90
#define BMP280_REGISTER_DIG_P3		0x92
#define BMP280_REGISTER_DIG_P4		0x94
#define BMP280_REGISTER_DIG_P5		0x96
#define BMP280_REGISTER_DIG_P6		0x98
#define BMP280_REGISTER_DIG_P7		0x9A
#define BMP280_REGISTER_DIG_P8		0x9C
#define BMP280_REGISTER_DIG_P9		0x9E

#define BMP280_REGISTER_CHIPID		0xD0
#define BMP280_REGISTER_VERSION		0xD1
#define BMP280_REGISTER_SOFTRESET	0xE0

#define BMP280_REGISTER_CAL26		0xE1  // R calibration stored in 0xE1-0xF0

#define BMP280_REGISTER_STATUS		0xF3
#define BMP280_REGISTER_CONTROL		0xF4
#define BMP280_REGISTER_CONFIG		0xF5
#define BMP280_REGISTER_PRESSUREDATA	0xF7
#define BMP280_REGISTER_TEMPDATA	0xFA

#define BMP280_WHOAMI			400
#define BMP280_RESET			401
#define BMP280_CFG			402
#define BMP280_CTRL			403
#define BMP280_GET_TEMP			404
#define BMP280_GET_PRESSURE		405
#define BMP280_GET_DIG_TEMP		406
#define BMP280_GET_DIG_PRESSURE		407
#define BMP280_STATUS			408

#endif
